const express=require('express');

const adminRouter=express.Router();
const adminController=require('../controllers/adminControllers');

adminRouter.post('/admit-student',adminController.postAdmitStudent);
adminRouter.get('/leave-requests',adminController.getLeaveRequests);
adminRouter.get('/admin/admin-complaints', adminController.getStudentComplaints);
adminRouter.put('/admin/admin-complaints/:id/complete', adminController.markComplaintCompleted);
adminRouter.get('/admin/attendance-rooms', adminController.getAttendanceStudentList);
adminRouter.post('/admin/attendance', adminController.saveAttendanceRecords);
adminRouter.get('/admin/leave-requests-status-update',adminController.getUpdateLeaveRequestStatus);
adminRouter.get('/admin/leave-history/students', adminController.getLeaveHistoryStudents);
adminRouter.get('/admin/leave-history', adminController.getLeaveHistoryForStudent);
adminRouter.get('/admin/notices', adminController.getNoticeBoard);
adminRouter.post('/admin/notices', adminController.createNotice);
adminRouter.put('/admin/notices/:id', adminController.updateNotice);
adminRouter.delete('/admin/notices/:id', adminController.deleteNotice);
adminRouter.get('/admin/rules-regulations', adminController.getRulesRegulations);
adminRouter.post('/admin/rules-regulations', adminController.createRuleRegulation);
adminRouter.put('/admin/rules-regulations/:id', adminController.updateRuleRegulation);
adminRouter.delete('/admin/rules-regulations/:id', adminController.deleteRuleRegulation);
adminRouter.get('/admin/alerts', adminController.getAlertBoard);
adminRouter.post('/admin/alerts', adminController.createAlert);
adminRouter.put('/admin/alerts/:id', adminController.updateAlert);
adminRouter.delete('/admin/alerts/:id', adminController.deleteAlert);
adminRouter.get('/admin/announcements', adminController.getAnnouncements);
adminRouter.post('/admin/announcements', adminController.createAnnouncement);
adminRouter.put('/admin/announcements/:id', adminController.updateAnnouncement);
adminRouter.delete('/admin/announcements/:id', adminController.deleteAnnouncement);
adminRouter.get('/admin/profile', adminController.getCurrentAdminProfile);
adminRouter.post('/admin/add-admin', adminController.postAddAdmin);
adminRouter.get('/admin/admins', adminController.getAllAdmins);
adminRouter.get('/admin/dashboard-stats', adminController.getDashboardStats);
adminRouter.get('/admin/students', adminController.getAllStudents);
adminRouter.get('/admin/attendance-history', adminController.getAttendanceHistory);
adminRouter.post('/admin/change-password', adminController.changeAdminPassword);
adminRouter.post('/admin/update-theme', adminController.updateAdminTheme);
adminRouter.get('/admin/mess-menu', adminController.getMessMenu);
adminRouter.post('/admin/mess-menu', adminController.createOrUpdateMessMenu);
adminRouter.put('/admin/mess-menu/:day/:mealType/:itemId', adminController.updateMessMenuItem);
adminRouter.delete('/admin/mess-menu/:day/:mealType/:itemId', adminController.deleteMessMenuItem);
module.exports=adminRouter;